import { CONTACTS_KEY } from 'store/storeKeys'

export const FETCH_CONTACTS_REQUEST = `${CONTACTS_KEY}/FETCH_CONTACTS_REQUEST`
export const FETCH_CONTACTS_SUCCESS = `${CONTACTS_KEY}/FETCH_CONTACTS_SUCCESS`
export const FETCH_CONTACTS_ERROR = `${CONTACTS_KEY}/FETCH_CONTACTS_ERROR`

export const APPLY_CONTACTS_SCOPE = `${CONTACTS_KEY}/APPLY_CONTACTS_SCOPE`
