import { CONTACT_KEY } from 'store/storeKeys'

export const FETCH_CONTACT_REQUEST = `${CONTACT_KEY}/FETCH_CONTACT_REQUEST`
export const FETCH_CONTACT_SUCCESS = `${CONTACT_KEY}/FETCH_CONTACT_SUCCESS`
export const FETCH_CONTACT_ERROR = `${CONTACT_KEY}/FETCH_CONTACT_ERROR`
